#%Module 1.0
#
#  MVAPICH2 module for use with 'environment-modules' package:
# 

# Define prefix so PATH and MANPATH can be updated.
setenv        prefix        /home/naser/encrypted-mpi-communication/encrypted-mvapich2-2.3/install
setenv        exec_prefix   ${prefix}
prepend-path  PATH          ${exec_prefix}/bin
prepend-path  MANPATH       ${prefix}/share/man

# Undefine prefix and exec_prefix which are too generic environment variables.
unsetenv      prefix
unsetenv      exec_prefix
